// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHistory: typeof import('./../src/components/admin/history.vue')['default']
    AdminMenu: typeof import('./../src/components/admin/menu.vue')['default']
    AdminNavbar: typeof import('./../src/components/admin/navbar.vue')['default']
    AdminNavbarBreadcrumb: typeof import('./../src/components/admin/navbar/breadcrumb.vue')['default']
    AdminNavbarNotification: typeof import('./../src/components/admin/navbar/notification.vue')['default']
    EditorEditor: typeof import('./../src/components/editor/editor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FormMyButton: typeof import('./../src/components/form/my-button.vue')['default']
    FormMyInput: typeof import('./../src/components/form/my-input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangWangeditor: typeof import('./../src/components/wang/wangeditor.vue')['default']
  }
}
